export const topics = [
  {
    "code": "A",
    "slug": "uiux",
    "title": "Cara Mengimplementasikan UI/UX",
    "shortTitle": "UI/UX",
    "route": "/uiux",
    "icon": "Palette",
    "summary": "Design thinking dari riset user sampai usability testing.",
    "accent": "from-pink-400 via-lime-300 to-cyan-300",
  },
  {
    "code": "B",
    "slug": "html",
    "title": "HTML",
    "shortTitle": "HTML",
    "route": "/html",
    "icon": "FileCode2",
    "summary": "Struktur dokumen, form, iframe, dan semantic HTML.",
    "accent": "from-orange-400 via-pink-300 to-yellow-300",
  },
  {
    "code": "C",
    "slug": "css-vanilla",
    "title": "CSS Vanilla",
    "shortTitle": "CSS",
    "route": "/css-vanilla",
    "icon": "Brush",
    "summary": "Selector, box model, dan specificity CSS lengkap.",
    "accent": "from-sky-400 via-lime-300 to-pink-300",
  },
  {
    "code": "D",
    "slug": "nodejs",
    "title": "Node JS & JS Dasar",
    "shortTitle": "Node JS",
    "route": "/nodejs",
    "icon": "SquareTerminal",
    "summary": "Node.js, npm, CLI, dan pondasi JavaScript.",
    "accent": "from-lime-400 via-emerald-300 to-cyan-300",
  },
  {
    "code": "E",
    "slug": "modern-js",
    "title": "Modern JS",
    "shortTitle": "Modern JS",
    "route": "/modern-js",
    "icon": "Sparkles",
    "summary": "ES6+, promise, async/await, module, dan array method.",
    "accent": "from-yellow-300 via-pink-300 to-cyan-300",
  },
  {
    "code": "F",
    "slug": "dom",
    "title": "DOM",
    "shortTitle": "DOM",
    "route": "/dom",
    "icon": "Network",
    "summary": "DOM tree, selector, manipulasi element, dan event.",
    "accent": "from-cyan-300 via-lime-300 to-pink-300",
  },
  {
    "code": "G",
    "slug": "tailwind",
    "title": "Tailwind",
    "shortTitle": "Tailwind",
    "route": "/tailwind",
    "icon": "Wind",
    "summary": "Utility-first, responsive, dark mode, dan workflow komponen.",
  },
  {
    "code": "H",
    "slug": "react",
    "title": "React",
    "shortTitle": "React",
    "route": "/react",
    "icon": "Atom",
    "summary": "Vite setup, component, props, state, effect, dan JSX.",
  },
  {
    "code": "I",
    "slug": "hostinger-vps",
    "title": "Hostinger VPS",
    "shortTitle": "VPS",
    "route": "/hostinger-vps",
    "icon": "Server",
    "summary": "Order VPS, SSH, Nginx, deploy app, domain, dan SSL.",
    "accent": "from-pink-400 via-yellow-300 to-lime-300",
  },
  {
    "code": "J",
    "slug": "putty",
    "title": "Putty",
    "shortTitle": "Putty",
    "route": "/putty",
    "icon": "KeyRound",
    "summary": "SSH ke VPS dari Windows dan command dasar server.",
    "accent": "from-lime-300 via-cyan-300 to-pink-300",
  },
  {
    "code": "K",
    "slug": "mysql-workbench",
    "title": "MySQL Workbench",
    "shortTitle": "MySQL",
    "route": "/mysql-workbench",
    "icon": "Database",
    "summary": "Install, koneksi, tipe data, function, operator, statement, dan studi kasus.",
    "accent": "from-blue-300 via-yellow-300 to-pink-300",
  }
]
